### ISSUE TITLE
There is a bug in the TeamPresenceWebPart.tsx

### ISSUE THREAD

**Issue by Ofer-Gal** [mpaukkon/SharePoint#1]
public componentDidMount(): void{
    console.log("Group ID:"+this.groupID);  //:39 Group ID:null
    if(this.groupID.length > 0)   //Cannot read property 'length' of null
    {    
      this._loadMembersAndPresence(this.groupID);
    }
   
  }

**Comment by mpaukkon** [comment]
This is now fixed.

**Comment by Ofer-Gal** [comment]
When running in /_layouts/15/workbench.aspx on a site with 6 members and me the owner, The line 81 `client.api("/groups/"+groupID+"/members").get().then(membersResponse => {` showes in the debugger: `https://graph.microsoft.com/v1.0/groups/503e6aad-6f34-42ee-b933-4cad58424e00/members 403 (Forbidden)` 
but running the same call in graph explorer, does show all the members.
I deployed to Sharepoint and added the web part in the team's site. But it is hitting the same 403  error.
Is there something I can do to allow this line to work? 
how did you test it?

**Comment by mpaukkon** [comment]
You need to approve API permissions for SharePoint Framework on SharePoint Admin Center. There should be Group.Read.All and Presence.Read.All Microsoft Graph permissions pending. 
Direct link to API management:
https://<tenant>-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement

**Comment by Ofer-Gal** [comment]
Thanks. 
Now I see the graphics on the workbench but not in an embedded web part.
The console shows:
`Access to XMLHttpRequest at 'https://waconatm.officeapps.live.com/apc/trans.gif?416e472b0562559419456648fea6d81b' from origin 'https://{mytenant}.sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource`
This is weird because everything is under https://{mytenant}.sharepoint.com even the workbench
